# Generated by Django 5.2.3 on 2025-06-27 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='looks/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('rotation', models.IntegerField(default=0)),
                ('scale', models.FloatField(default=1.0)),
                ('z_index', models.IntegerField(default=0)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.clothingitem')),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitting_room.look')),
            ],
            options={
                'ordering': ['z_index'],
            },
        ),
        migrations.AddField(
            model_name='look',
            name='items',
            field=models.ManyToManyField(through='fitting_room.LookItem', to='closet.clothingitem'),
        ),
    ]
