# Generated by Django 5.2.3 on 2025-08-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='look',
            name='image',
            field=models.ImageField(blank=True, upload_to='looks/'),
        ),
    ]
