# Generated by Django 5.2.3 on 2025-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='look',
            name='items',
        ),
        migrations.AlterField(
            model_name='look',
            name='image',
            field=models.ImageField(blank=True, upload_to='looks/'),
        ),
        migrations.DeleteModel(
            name='LookItem',
        ),
    ]
