# Generated by Django 5.2.3 on 2025-08-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting_room', '0002_alter_look_image'),
        ('fitting_room', '0002_remove_look_items_alter_look_image_delete_lookitem'),
    ]

    operations = [
    ]
