# Generated by Django 5.2.3 on 2025-06-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='category',
        ),
    ]
