# Generated by Django 5.2.1 on 2025-05-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='banner',
            new_name='image',
        ),
    ]
