<<<<<<< HEAD:posts/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 75)
    category = models.TextField(blank=True) #different from Charfield, relates to a text area form input
    slug = models.SlugField(blank=True) #unused, urls generated by pk, left here for future deployments relating to slugs
    date = models.DateTimeField(auto_now_add = True) #auto adds date and time
    image = models.ImageField(default='fallback.jpeg', blank = True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    tags = TaggableManager()
    
    def __str__(self):
        return self.title

class Outfit(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Post)
    date = models.DateTimeField(auto_now_add=True) 
=======
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.
class ClothingItem(models.Model):
    title = models.CharField(max_length = 75)
    slug = models.SlugField(blank=True) #unused, urls generated by pk, left here for future deployments relating to slugs
    date = models.DateTimeField(auto_now_add = True) #auto adds date and time
    image = models.ImageField(default='fallback.jpeg', blank = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    tags = TaggableManager()
    
    def __str__(self):
        return self.title


>>>>>>> main:closet/models.py
